version: '3.9'

services:
  dind:
    image: docker:20.10-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-storage:/var/lib/docker
    networks:
      - jenkins-net

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - dind
    networks:
      - jenkins-net

volumes:
  jenkins_home:
  dind-storage:

networks:
  jenkins-net:
